// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:520668169266:web:0e9a6b1cc18275031ba82b',
    messagingSenderId: '520668169266',
    projectId: 'inclusilearn-f8863',
    authDomain: 'inclusilearn-f8863.firebaseapp.com',
    storageBucket: 'inclusilearn-f8863.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:520668169266:android:857b6ddab310b7341ba82b',
    messagingSenderId: '520668169266',
    projectId: 'inclusilearn-f8863',
    storageBucket: 'inclusilearn-f8863.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:520668169266:ios:6071711c5bcb14591ba82b',
    messagingSenderId: '520668169266',
    projectId: 'inclusilearn-f8863',
    storageBucket: 'inclusilearn-f8863.firebasestorage.app',
    iosBundleId: 'com.example.inclusilearn',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:520668169266:ios:6071711c5bcb14591ba82b',
    messagingSenderId: '520668169266',
    projectId: 'inclusilearn-f8863',
    storageBucket: 'inclusilearn-f8863.firebasestorage.app',
    iosBundleId: 'com.example.inclusilearn',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:520668169266:web:674b34a4104c03fc1ba82b',
    messagingSenderId: '520668169266',
    projectId: 'inclusilearn-f8863',
    authDomain: 'inclusilearn-f8863.firebaseapp.com',
    storageBucket: 'inclusilearn-f8863.firebasestorage.app',
  );

}